# Site settings
title: chowson.github.io
#header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: chowson.github.io
github_username:  chowson

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
