# Site settings
title: chowson.github.io
#header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: chowson.github.io
github_username:  chowson
url: https://chowson.github.io

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 5
exclude: ["less", "ts","node_modules","Gruntfile.js","package.json","README.md","docker-compose.yml"]

kramdown:
  syntax_highlighter: rouge

# Plugins
gems: [jekyll-paginate]