# Site settings
title: Sitecore ASP.NET, and software development
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Posts about Sitecore, ASP.NET and software development"
#baseurl: "/startbootstrap-clean-blog-jekyll"
#url: "http://yourdomain.com"
#twitter_username: SBootstrap
github_username:  chowson
#facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

#http://www.hossainmohdfaysal.com/Notepad/