name: Check Website Pages

on:
  push:
    branches: [ master ]

jobs:
  test-sitemap-links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    
    - name: Check URLs
      uses: paramt/url-checker@master
      with:
        files: "sitemap.xml"
        blacklist: "http://www.w3.org/1999/xhtml,http://www.google.com/schemas/sitemap-mobile/1.0"
